version: "3.8"
services:
  webapp:
    build: ./suraromu
    container_name: suraromu_webapp_c
    volumes:
      - ./suraromu:/w_app
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - mynetwork
  solver:
    build: ./solver
    container_name: solver_python_c
    restart: on-failure
    ports:
      - "5000:5000"
    volumes:
      - ./solver:/s_app
    networks:
      - mynetwork
  generator:
    build: ./generator
    container_name: generator_python_c
    restart: on-failure
    ports:
      - "4000:4000"
    volumes:
      - ./generator:/g_app
    networks:
      - mynetwork
networks:
  mynetwork:
